version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerenGH_AzAU_0202Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
